# Generated by Django 4.0.5 on 2022-06-06 09:20

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaing',
            options={'ordering': ('-created',), 'verbose_name': 'Campaing', 'verbose_name_plural': 'Campaings'},
        ),
        migrations.AddField(
            model_name='campaing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaing',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaing',
            name='image',
            field=cloudinary.models.CloudinaryField(default=' ', max_length=255, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
